-- ============================================================
-- Walletzey — Migration SQL para Supabase
-- Execute no SQL Editor do Supabase
-- ============================================================

-- 1. Criação da tabela principal
create table public.walletzey (
  id bigint generated by default as identity not null,
  data date null,
  debito numeric null,
  credito numeric null,
  valor numeric null,
  categoria character varying null,
  recorrente boolean null default false,
  created_at timestamp with time zone not null default now(),
  descricao text null,
  tipo_recorrencia character varying null,
  parcelas_total integer null,
  parcela_atual integer null,
  dia_cobranca integer null,
  hash_extrato character varying(64) null,
  fonte character varying null default 'manual'::character varying,
  constraint walletzey_pkey primary key (id)
) TABLESPACE pg_default;


-- 2. Tabela de categorias
CREATE TABLE IF NOT EXISTS public.categorias (
  id         bigint generated by default as identity not null,
  nome       character varying not null,
  cor        character varying,
  icone      character varying,
  created_at timestamp with time zone not null default now(),
  constraint categorias_pkey primary key (id),
  constraint categorias_nome_key unique (nome)
);

-- 3. Tabela de recorrentes
CREATE TABLE IF NOT EXISTS public.recorrentes (
  id               bigint generated by default as identity not null,
  descricao        character varying not null,
  valor            numeric not null,
  tipo_recorrencia character varying not null,
  parcelas_total   integer,
  parcela_atual    integer,
  dia_cobranca     integer,
  categoria        character varying,
  ativo            boolean not null default true,
  created_at       timestamp with time zone not null default now(),
  constraint recorrentes_pkey primary key (id)
);

-- 4. Tabela de controle de extratos importados (deduplicação)
CREATE TABLE IF NOT EXISTS public.extratos_importados (
  id           bigint generated by default as identity not null,
  hash         character varying(64) not null,
  nome_arquivo character varying,
  importado_em timestamp with time zone not null default now(),
  constraint extratos_importados_pkey primary key (id),
  constraint extratos_importados_hash_key unique (hash)
);
